"""The fixed texts of the minutes' email, PDF and Markdown, per language of the minutes (see
builder.MINUTES_LANGUAGES)."""

LABELS = {
    "en": {
        "medical": "Medical meeting", "executive": "Executive meeting", "administrative": "Administrative meeting",
        "minutes": "Minutes", "held": "Held", "approved": "Approved by", "approved_by": "approved by {name}",
        "summary": "Summary", "key_moments": "Key moments", "topics": "Topics", "topic": "Topic",
        "status": "Status", "findings": "Findings", "decisions": "Decisions", "other_decisions": "Other decisions",
        "action_items": "Action items", "task": "Task", "owner": "Owner", "deadline": "Deadline",
        "priority": "Priority", "priorities": {"high": "high", "medium": "medium", "low": "low"},
        "open_issues": "Open issues", "present": "Present", "participants": "Participants",
        "verification": "Verification notes",
        "min_s": "{m} min {s:02d} s", "h_min": "{h} h {m:02d} min",
        "meeting": "Meeting", "duration": "Duration", "page": "Page", "of": "of",
        "greeting": "Hello,", "cover": "Please find attached the minutes of the meeting “{meeting}” held on {date}.",
        "cover_approved": "They were approved by {name}.", "regards": "Kind regards,",
    },
    "ro": {
        "medical": "Ședință medicală", "executive": "Ședință de conducere", "administrative": "Ședință administrativă",
        "minutes": "Proces-verbal", "held": "Data", "approved": "Aprobat de", "approved_by": "aprobat de {name}",
        "summary": "Rezumat", "key_moments": "Momente-cheie", "topics": "Subiecte", "topic": "Subiect",
        "status": "Stare", "findings": "Constatări", "decisions": "Decizii", "other_decisions": "Alte decizii",
        "action_items": "Sarcini", "task": "Sarcină", "owner": "Responsabil", "deadline": "Termen",
        "priority": "Prioritate",
        "priorities": {"high": "ridicată", "medium": "medie", "low": "scăzută"},
        "open_issues": "Probleme nerezolvate", "present": "Prezenți", "participants": "Participanți",
        "verification": "Note de verificare",
        "min_s": "{m} min {s:02d} s", "h_min": "{h} h {m:02d} min",
        "meeting": "Ședința", "duration": "Durata", "page": "Pagina", "of": "din",
        "greeting": "Bună ziua,", "cover": "Vă transmitem atașat procesul-verbal al ședinței „{meeting}” din {date}.",
        "cover_approved": "Acesta a fost aprobat de {name}.", "regards": "Cu stimă,",
    },
    "ru": {
        "medical": "Медицинское совещание", "executive": "Совещание руководства",
        "administrative": "Административное совещание",
        "minutes": "Протокол", "held": "Дата", "approved": "Утверждено", "approved_by": "утверждено: {name}",
        "summary": "Краткое содержание", "key_moments": "Ключевые моменты", "topics": "Темы", "topic": "Тема",
        "status": "Состояние", "findings": "Данные", "decisions": "Решения", "other_decisions": "Другие решения",
        "action_items": "Поручения", "task": "Поручение", "owner": "Ответственный", "deadline": "Срок",
        "priority": "Приоритет",
        "priorities": {"high": "высокий", "medium": "средний", "low": "низкий"},
        "open_issues": "Открытые вопросы", "present": "Присутствовали", "participants": "Участники",
        "verification": "Замечания по проверке",
        "min_s": "{m} мин {s:02d} с", "h_min": "{h} ч {m:02d} мин",
        "meeting": "Совещание", "duration": "Продолжительность", "page": "Страница", "of": "из",
        "greeting": "Здравствуйте!", "cover": "Во вложении — протокол совещания «{meeting}» от {date}.",
        "cover_approved": "Протокол утверждён: {name}.", "regards": "С уважением,",
    },
}
